[landing_zone]
    base_path         = "/Users/production-didierarchambault/Documents/Workbench_dev/augmentis/CWB_bronze_layer/tests/mock_data/landing_zone/initial_load"
    path_layout       = "{source}/{x_center}/{step}/{status}/{table}"


[bronze]
    db_path                  = "fake_temp_path"
    path_layout              = "{source}/{x_center}/{step}/{status}/{table}"
    columns_to_clean_rules   = "bll/ressources/dictionaries/bronze_cleaning.json"
    columns_rename_map       = "bll/ressources/dictionaries/bronze_rename_map.json"
    bronze_technicals        = "bll/ressources/dictionaries/bronze_technicals.json"


[bronze_technicals]
    Row_Hash_ID        = true
    Ingestion_Run_ID   = true
    Schema_ID          = true
    Ingest_Timestamp   = true
    Claim_SK           = true
    Hash_Cols          = ["id", "siulifecyclestate"] # adjust claim_id (we clean before we do technicals)
    Surrogate_Cols     = ["id", "siulifecyclestate"]


[bronze_columns_mapping]
    id                       = "claim_id"
    siulifecyclestate        = "siulifecyclestate"


[silver]
    db_path           = "fake_temp_path"
    path_layout       = "{source}/{x_center}/{step}/{status}/{table}" # to be revised


[gold]
    db_path           = "fake_temp_path"
    path_layout       = "{source}/{x_center}/{step}/{status}/{table}" # to be revised


[tests]
    gold_path          = "fake_temp_path"


[logging]
    main_logging_path         = "/Users/production-didierarchambault/Documents/Workbench_dev/augmentis/CWB_bronze_layer/dal/run_logs"

